# Generated by Django 4.2 on 2025-01-12 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizeattribute',
            options={'ordering': ['product_variant', 'size', 'attribute'], 'verbose_name': 'Product Size Attribute', 'verbose_name_plural': 'Product Size Attributes'},
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='The image of the product variant.', upload_to='product_variant_images/', verbose_name='Image')),
                ('is_primary', models.BooleanField(default=False, help_text='Indicates if this is the primary image for the product variant.', verbose_name='Primary Image')),
                ('variant', models.ForeignKey(help_text='The product variant this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='store.productvariant', verbose_name='Product Variant')),
            ],
            options={
                'verbose_name': 'Product Variant Image',
                'verbose_name_plural': 'Product Variant Images',
                'ordering': ['created'],
            },
        ),
    ]
